//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseTea3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Ratings = new HashSet<Rating>();
            this.ShRecords = new HashSet<ShRecord>();
        }
    
        public int ID { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<ShRecord> ShRecords { get; set; }
    }
}
