//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseTea3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public int ProductId { get; set; }
        public int CommentId { get; set; }
        public int RatingValue { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Order Order { get; set; }
        public virtual ProductComment ProductComment { get; set; }
        public virtual TeaProduct TeaProduct { get; set; }
    }
}
