//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseTea3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShRecord
    {
        public int ID { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime AddTime { get; set; }
        public string UserId { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Order Order { get; set; }
        public virtual TeaProduct TeaProduct { get; set; }
    }
}
