//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChineseTea3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeaProduct
    {
        public TeaProduct()
        {
            this.ProductComments = new HashSet<ProductComment>();
            this.Ratings1 = new HashSet<Rating>();
            this.ShRecords = new HashSet<ShRecord>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Origin { get; set; }
        public bool Status { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string Kind { get; set; }
        public string ImageFileName { get; set; }
        public int Count { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> Ratings { get; set; }
    
        public virtual ICollection<ProductComment> ProductComments { get; set; }
        public virtual ICollection<Rating> Ratings1 { get; set; }
        public virtual ICollection<ShRecord> ShRecords { get; set; }
    }
}
